const LIST_SEARCH_PARAM_KEY = 'keyword'

/** 分页组件  */
const LIST_PAGE_PARAM_KEY = 'page'
const LIST_PAGE_SIZE_PARAM_KEY = 'pageSize'
const LIST_DEFAULT_PAGE_SIZE = '10'

export {
  LIST_SEARCH_PARAM_KEY,
  LIST_PAGE_PARAM_KEY,
  LIST_PAGE_SIZE_PARAM_KEY,
  LIST_DEFAULT_PAGE_SIZE
}
